### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by UweBonnes** [majbthrd/DapperMime#1]
There  is no version number available from the info command:

cmd :   00.04.
cmd res:00.06.04.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.

**Comment by majbthrd** [comment]
It works just fine here; I've not been able to replicate what you are seeing.  I've attached quick and dirty source code that produces the following output:

W: 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
R: 00 06 32 2e 30 2e 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

Moreover, if anyone runs openocd, they will see:

Info : Hardware thread awareness created
Info : RP2040 Flash Bank Command
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  Supported
**Info : CMSIS-DAP: FW Version = 2.0.0**
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 0 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 4000 kHz

Which devices have previously tested your CMSIS-DAP implementation against?

Thanks.

**Comment by majbthrd** [comment]
@UweBonnes, I'm not aware of any USB requirement that a USB device must have an iManufacturer and iSerial string.  Omitting them is a legitimate USB configuration.  Even a device name isn't a USB requirement, but it is for CMSIS-DAP in order for the debugger to be detected.  pico-debug is designed to fit into as small as possible a RAM image, and adding unnecessary functionality hurts this objective.

For example code on enumerating CMSIS-DAP adapters, please take a look at the sample code I provided you in [one of the other issues you created]( https://github.com/majbthrd/DapperMime/issues/1).  You could also look at OpenOCD, where it just so happens that I contributed the PR for CMSIS-DAP detection some years ago.

**Comment by UweBonnes** [comment]
I compiled "make BOARD=stm32f103bluepill" and "make BOARD=raspberry_pi_pico" and flashed  and both report no Version string with blackmagic hosted where my other  CMSIS DAP board show a valid version string. However dapinfo also show the version string on bluepill ans pico, so the HID handling in blackmagic needs a kick. Thanks for the small example!
