### ISSUE TITLE
Provide boardname as amufacturer

### ISSUE THREAD

**Issue by UweBonnes** [majbthrd/DapperMime#3]
Appended patch helps to differentiate at least Dappermime on different boards.
[dappermime.diff.gz](https://github.com/majbthrd/DapperMime/files/5988180/dappermime.diff.gz)

**Comment by majbthrd** [comment]
Sorry, you are "a day late and a dollar short" to use an expression... did you not see that I've already added such a capability?

Moreover, your diff only works for boards that use Makefile; rp2040, for example, does not use Makefile.  Please try the code already available.
