### ISSUE TITLE
Provide new Raspberry Pi Pico version

### ISSUE THREAD

**Issue by ctron** [majbthrd/DapperMime#4]
The provided version for the Raspberry Pi in the releases section didn't work for me. I had to re-compile the most recent main branch and that fixed it for me.

Here is a binary that works (if you trust me :grin:)

[raspberry_pi_pico-DapperMime.uf2.gz](https://github.com/majbthrd/DapperMime/files/6672406/raspberry_pi_pico-DapperMime.uf2.gz)

For a good getting started experience, it would be great to have a ready to flash binary.

**Comment by majbthrd** [comment]
That makes sense.  The previous download corresponding to an early version of the code that did something completely different from the present code.  The early code evolved into [pico-debug](https://github.com/majbthrd/pico-debug) where one RP2040 debugs itself, and this code became an alternative to the proprietary [picoprobe](https://github.com/raspberrypi/picoprobe) where one RP2040 debugs a second RP2040.

I have added a download to the Releases.
