### ISSUE TITLE
Pico SDK No Longer Submodule in TinyUSB

### ISSUE THREAD

**Issue by a-gavin** [majbthrd/DapperMime#9]
https://github.com/majbthrd/DapperMime/blob/e5e92ee4f9e43d8408c4cd65677aaee0495365f1/CMakeLists.txt#L12

I realize this project may not be actively maintained, but I just want to point out for others who may also try building from source that TinyUSB [no longer includes the Pico SDK as a submodule](https://github.com/hathach/tinyusb/commit/bebc910447bc4208977f2cc055db306713f48030#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584) as of April 2021, breaking the build script for this project.

Only after fiddling with things for a bit did I realize that there are pre-compiled images available for download in the Releases section of the repo. Linking [here](https://github.com/majbthrd/DapperMime/releases) for reference.

**Comment by majbthrd** [comment]
Ah, with hindsight I think what happened was that when I updated to the latest TinyUSB on Dec 18, 2021 (only a month ago... I didn't realize such a small time qualified as "not actively maintained"), my existing local build still worked despite the April 2021 change that you refer to.  I'll look at it when I next get a chance.  You could have just used the previous commit (and updated the submodules to use the previous vintage), and all would have been fine.

I don't know what I have to do to make the Releases tab more obvious... do I need to put something in the README.md?

**Comment by a-gavin** [comment]
Apologies, I meant no offense by that comment. Didn't want to make you feel pressure to fix this :smile: 

I don't entirely recall but I believe using the previous commit may have worked for me as well. Downloading from the Releases tab certainly did the trick, though.

I actually only found out about the pre-compiled executable through the [rp2040-project-template repo](https://github.com/rp-rs/rp2040-project-template#requirements), if that goes to show you how trained my brain is to look at Releases. I think an update to the README.md would suffice.

**Comment by majbthrd** [comment]
The Dec 2021 update was meant to be a straightforward, low-risk update to keep current with TinyUSB, but I was mistaken! :(

Anyway, I'm made two additional commits: one adds to the README.md to point to the Releases, and the other more involved change was adding pico-sdk to the submodules and updating the CMakeList dependencies to work with the latest pico_sdk build process.  This should address the issues you raised.
